11feb/EmployeeDataServices/EmployeeDataServices/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmployeeData;
using EmployeeDataServices.Models;

namespace EmployeeDataServices.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly DataContext _context;

        public DepartmentsController(DataContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Departments.ToListAsync());
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }
            var employeeList = _context.Employees.Include(e => e.Department).Where(i => i.DepartmentId == id).Select(e => new EmployeeDetail
            {
                EmployeeName = e.EmployeeName,
                Email = e.Email,
                DOB = e.DOB,
                State = e.State,
                Address = e.Address,
                City = e.City,
                Id = e.Id,
                Zip = e.Zip,
                Phone = e.Phone,
                JoiningDate = e.JoiningDate,
                DepartmentName = e.Department.DepartmentName
            }).ToListAsync();
          //  ViewBag.Count = _context.Employees.Include(e => e.Department).Where(e=>e.DepartmentId==id).Count();
            return View(await employeeList);
        }

        // GET: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DepartmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DepartmentName")] Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var department = await _context.Departments.FindAsync(id);
            _context.Departments.Remove(department);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
            return _context.Departments.Any(e => e.Id == id);
        }
    }
}

11feb/EmployeeDataServices/EmployeeDataServices/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmployeeData;
using EmployeeDataServices.Models;

namespace EmployeeDataServices.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly DataContext _context;
        private readonly IEmployeeRepository _employeeRepository;
        public EmployeesController(DataContext context, IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            if (ModelState.IsValid)
            {
                var emp = _context.Employees.Include(e => e.Department).Select(e => new EmployeeDetail
                {
                    Id = e.Id,
                    EmployeeName = e.EmployeeName,
                    DOB = e.DOB,
                    Phone = e.Phone,
                    Email = e.Email,
                    Address = e.Address,
                    State = e.State,
                    City = e.City,
                    Zip = e.Zip,
                    DepartmentName = e.DepartmentName
                });
                return View(await emp.ToListAsync());
            }
            else
            { return RedirectToRoute("Index"); }
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                 .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return RedirectToRoute("Create");
            }
            EmployeeDetail emp = _employeeRepository.ChangeEmployee(employee);
            return View(emp);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            ViewBag.State = new SelectList(_context.States, "StateName", "StateName");
            List<Department> departments = _context.Departments.ToList();
            ViewBag.DepartmentName = new SelectList(departments, "DepartmentName", "DepartmentName");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Employee employee)
        {

            employee.DepartmentId = _context.Departments.Where(d => d.DepartmentName.Equals(employee.DepartmentName)).Select(f => f.Id).SingleOrDefault();
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            EmployeeDetail emp = _employeeRepository.ChangeEmployee(employee);
            ViewBag.State = new SelectList(_context.States, "StateName", "StateName");
            List<Department> departments = _context.Departments.ToList();
            ViewBag.DepartmentName = new SelectList(departments, "DepartmentName", "DepartmentName");
            return View(emp);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            EmployeeDetail emp = _employeeRepository.ChangeEmployee(employee);
            ViewBag.City = new SelectList(_context.Cities.Where(x => x.State.StateName == employee.State), "CityName", "CityName");
            ViewBag.State = new SelectList(_context.States, "StateName", "StateName");
            List<Department> departments = _context.Departments.ToList();
            ViewBag.DepartmentName = new SelectList(departments, "DepartmentName", "DepartmentName");
            return View(emp);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Employee employee)
        {
            employee.DepartmentId = _context.Departments.Where(d => d.DepartmentName.Equals(employee.DepartmentName)).Select(f => f.Id).SingleOrDefault();
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            List<Department> departments = _context.Departments.ToList();
            ViewBag.DepartmentName = new SelectList(departments, "DepartmentName", "DepartmentName");
            return View(employee);
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
    }
}

11feb/EmployeeDataServices/EmployeeDataServices/Views/Shared/_Detail.cshtml
 
@model EmployeeDataServices.Models.EmployeeDetail
@{
    ViewData["Title"] = "_Detail";
}

<div class="form-group row">
    <label asp-for="EmployeeName" class="col-md-4 font-weight-bold col-form-label"></label>
    <div class="col-md-8">
        <th:input asp-for="EmployeeName" class="col-md-4 col-form-label"/>
    </div>
</div>
<div class="form-group row">
    <label asp-for="DOB" class="col-md-4 font-weight-bold col-form-label"></label>
    <div class="col-md-8">
        <label asp-for="DOB" class="col-md-4 col-form-label"></label>
    </div>
</div>
<div class="form-group row">
    <label asp-for="City" class="col-md-4 font-weight-bold col-form-label"></label>
    <div class="col-md-8">
        <label asp-for="City" class="col-md-4 col-form-label"></label>
    </div>
</div>
<div class="form-group row">
    <label asp-for="State" class="col-md-4 font-weight-bold col-form-label"></label>
    <div class="col-md-8">
        <label asp-for="State" class="col-md-4 col-form-label"></label>
    </div>
</div>
<div class="form-group row">
    <label asp-for="DepartmentName" class="col-md-4 font-weight-bold col-form-label"></label>
    <div class="col-md-8">
        <label asp-for="DepartmentName" class="col-md-4 col-form-label"></label>
    </div>
</div>
<div class="form-group row">
    <label asp-for="JoiningDate" class="col-md-4 font-weight-bold col-form-label"></label>
    <div class="col-md-8">
        <label asp-for="JoiningDate" class="col-md-4 col-form-label"></label>
    </div>
</div>
<div class="form-group row">
    <label asp-for="Email" class="col-md-4 font-weight-bold col-form-label"></label>
    <div class="col-md-8">
        <label asp-for="Email" class="col-md-4 col-form-label"></label>
    </div>
</div>
<div class="form-group row">
    <label asp-for="Phone" class="col-md-4 font-weight-bold col-form-label"></label>
    <div class="col-md-8">
        <label asp-for="Phone" class="col-md-4 col-form-label"></label>
    </div>
</div>
<div class="form-group row">
    <label asp-for="Zip" class="col-md-4 font-weight-bold col-form-label"></label>
    <div class="col-md-8">
        <label asp-for="Zip" class="col-md-4 col-form-label"></label>
    </div>
</div>
<div class="form-group row">
    <label asp-for="Address" class="col-md-4 font-weight-bold col-form-label"></label>
    <div class="col-md-8">
        <label asp-for="Address" class="col-md-4 col-form-label"></label>
    </div>
</div>

11feb/EmployeeDataServices/EmployeeDataServices/Views/Shared/_Form.cshtml
@model EmployeeDataServices.Models.EmployeeDetail
@{
    ViewData["Title"] = "_Form";
}
<div class="form-group row">
    <label asp-for="EmployeeName" class="col-md-5 font-weight-bold col-form-label"></label>
    <div class="col-md-7">
        <input asp-for="EmployeeName" class="form-control" />
        <span asp-validation-for="EmployeeName" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <label asp-for="DOB" class="col-md-5 font-weight-bold col-form-label"></label>
    <div class="col-md-7">
        <input asp-for="DOB" id="dob" type="text" class="form-control" />
        <span asp-validation-for="DOB" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <label asp-for="City" class="col-md-5 font-weight-bold col-form-label"></label>
    <div class="col-md-7">
        <select asp-for="City" class="form-control" id="city"></select>
        <span asp-validation-for="City" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <label asp-for="State" class="col-md-5 font-weight-bold col-form-label"></label>
    <div class="col-md-7">
        <select asp-for="State" class="form-control" asp-items="ViewBag.State" onchange="GetCity(this.value)">
            <option disabled selected hidden>Choose State</option>
        </select>
        <span asp-validation-for="State" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <label asp-for="DepartmentName" class="col-md-5 font-weight-bold col-form-label"></label>
    <div class="col-md-7">
        <select asp-for="DepartmentName" class="form-control" asp-items="ViewBag.DepartmentName"></select>
        <span asp-validation-for="DepartmentName" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <label asp-for="JoiningDate" class="col-md-5 font-weight-bold col-form-label"></label>
    <div class="col-md-7">
        <input asp-for="JoiningDate" id="join" type="text" class="form-control" />
        <span asp-validation-for="JoiningDate" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <label asp-for="Email" class="col-md-5 font-weight-bold col-form-label"></label>
    <div class="col-md-7">
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <label asp-for="Phone" class="col-md-5 font-weight-bold col-form-label"></label>
    <div class="col-md-7">
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <label asp-for="Zip" class="col-md-5 font-weight-bold col-form-label"></label>
    <div class="col-md-7">
        <input asp-for="Zip" class="form-control" />
        <span asp-validation-for="Zip" class="text-danger"></span>
    </div>
</div>
<div class="form-group row">
    <label asp-for="Address" class="col-md-5 font-weight-bold col-form-label"></label>
    <div class="col-md-7">
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
</div>

11feb/EmployeeDataServices/EmployeeDataServices/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeDataServices</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Employees" asp-action="Index">EmployeeDataServices</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EmployeeDataServices - <a asp-area="" asp-controller="Employees" asp-action="index">Employees</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>